-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Country"
(
    "ID_Country" serial NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT "Country_pkey" PRIMARY KEY ("ID_Country")
);

CREATE TABLE IF NOT EXISTS public."Environmental Indicator"
(
    "ID_Environmental" serial NOT NULL,
    "ELUC" numeric(15, 10),
    "CO2_Emision" numeric(15, 10),
    "Year" integer,
    "Country_ID" integer,
    CONSTRAINT "Environmental Indicator_pkey" PRIMARY KEY ("ID_Environmental")
);

CREATE TABLE IF NOT EXISTS public."Investiment"
(
    "ID_Investiment" serial NOT NULL,
    "GDP" numeric(12, 2),
    "Investment_Energy" numeric(15, 2),
    "Health_Expenditure" numeric(15, 2),
    "Year" integer,
    "Country_ID" integer,
    CONSTRAINT "GDP_pkey" PRIMARY KEY ("ID_GDP")
);

CREATE TABLE IF NOT EXISTS public."Development"
(
    "ID_Development" serial NOT NULL,
    "IDH" numeric(6, 2),
    "Electricity" numeric(6, 2),
    "Sanitation" numeric(6, 2),
    "Health" numeric(6, 2),
    "Standard_Living" numeric(6, 2),
    "Ano" integer,
    "Country_ID" integer,
    CONSTRAINT "IDH_pkey" PRIMARY KEY ("ID_IDH")
);

CREATE TABLE IF NOT EXISTS public."Power Consumed"
(
    "ID_Consumed" serial NOT NULL,
    "GWH" numeric(12, 2),
    "PowerImport" numeric(12, 2),
    "Renewable_Energy" numeric(7, 4),
    "Year" integer,
    "Country_ID" integer,
    CONSTRAINT "Power Consumed_pkey" PRIMARY KEY ("ID_Consumed")
);

CREATE TABLE IF NOT EXISTS public."Power Source"
(
    "ID_Power" serial NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default",
    "Renewable" boolean,
    CONSTRAINT "Power Source_pkey" PRIMARY KEY ("ID_Power")
);

CREATE TABLE IF NOT EXISTS public."Sector"
(
    "ID_Sector" serial NOT NULL,
    "Name" character varying(100) COLLATE pg_catalog."default",
    "Descrição" character varying(200),
    CONSTRAINT "Sector_pkey" PRIMARY KEY ("ID_Sector")
);

CREATE TABLE IF NOT EXISTS public."Sector_Country"
(
    "Sector_ID_Sector" serial NOT NULL,
    "Country_ID_Country" serial NOT NULL,
    "CO2_Emission" numeric(12, 4),
    "Year" integer
);

CREATE TABLE IF NOT EXISTS public."Power Source_Country"
(
    "Power Source_ID_Power" serial NOT NULL,
    "Country_ID_Country" serial NOT NULL,
    "Year" integer,
    "CO2_Emission" numeric(12, 4),
    "Power_Generati" numeric(12, 4)
);

CREATE TABLE IF NOT EXISTS public."Population_Year"
(
    "ID" serial NOT NULL,
    "Year" integer,
    "Population" integer,
    "Country_ID" integer
);

ALTER TABLE IF EXISTS public."Environmental Indicator"
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Investiment"
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Development"
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Power Consumed"
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sector_Country"
    ADD FOREIGN KEY ("Sector_ID_Sector")
    REFERENCES public."Sector" ("ID_Sector") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Sector_Country"
    ADD FOREIGN KEY ("Country_ID_Country")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Power Source_Country"
    ADD FOREIGN KEY ("Power Source_ID_Power")
    REFERENCES public."Power Source" ("ID_Power") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Power Source_Country"
    ADD FOREIGN KEY ("Country_ID_Country")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Population_Year"
    ADD FOREIGN KEY ("Country_ID")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;