-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Country"
(
    "ID_Country" integer NOT NULL,
    "Name" character varying(10) COLLATE pg_catalog."default",
    "Region" character varying COLLATE pg_catalog."default",
    CONSTRAINT "Country_pkey" PRIMARY KEY ("ID_Country")
);

CREATE TABLE IF NOT EXISTS public."Country_Power Source"
(
    "Country_ID_Country" integer,
    "Power Source_ID_Power" integer,
    "Year_ID_year" integer
);

CREATE TABLE IF NOT EXISTS public."Country_Year"
(
    "Country_ID_Country" integer,
    "Year_ID_year" integer,
    "GDP_ID" integer,
    "IDH_ID" integer,
    "Enviromental_ID" integer,
    "ConsumePower_ID" integer,
    "Power Generation" integer,
    CONSTRAINT "Country_Year_Enviromental_ID_key" UNIQUE ("Enviromental_ID"),
    CONSTRAINT "Country_Year_GDP_ID_key" UNIQUE ("GDP_ID"),
    CONSTRAINT "Country_Year_IDH_ID_key" UNIQUE ("IDH_ID")
);

CREATE TABLE IF NOT EXISTS public."Environmental Indicator"
(
    "ID_Environmental" integer NOT NULL,
    "Low_Carbon" integer,
    "Reneable" integer,
    "CO2_Emision" integer,
    CONSTRAINT "Environmental Indicator_pkey" PRIMARY KEY ("ID_Environmental")
);

CREATE TABLE IF NOT EXISTS public."GDP"
(
    "ID_GDP" integer NOT NULL,
    "GDP" integer,
    "Population" integer,
    "Health_Expendicture" integer,
    CONSTRAINT "GDP_pkey" PRIMARY KEY ("ID_GDP")
);

CREATE TABLE IF NOT EXISTS public."IDH"
(
    "ID_IDH" integer NOT NULL,
    "IDH" integer,
    "Eletricity" integer,
    "Sanitation" integer,
    "Health" integer,
    "Standard_Living" integer,
    CONSTRAINT "ID_IDH" PRIMARY KEY ("ID_IDH")
);

CREATE TABLE IF NOT EXISTS public."Power Consumed"
(
    "ID_Consumed" integer NOT NULL,
    "GWH" integer,
    "PowerImport" integer,
    CONSTRAINT "Power Consumed_pkey" PRIMARY KEY ("ID_Consumed")
);

CREATE TABLE IF NOT EXISTS public."Power Source"
(
    "ID_Power" integer NOT NULL,
    "Name" character varying(30) COLLATE pg_catalog."default",
    "Renewable" boolean,
    CONSTRAINT "Power Source_pkey" PRIMARY KEY ("ID_Power")
);

CREATE TABLE IF NOT EXISTS public."Setor"
(
    "ID_Server" integer NOT NULL,
    "Name" character varying(10) COLLATE pg_catalog."default",
    "Descrition" character varying(30),
    CONSTRAINT "Setor_pkey" PRIMARY KEY ("ID_Server")
);

CREATE TABLE IF NOT EXISTS public."Setor_Year"
(
    "Setor_ID_Server" integer,
    "Year_ID_year" integer,
    "Country_ID_country" integer,
    "CO2_Emission" integer
);

CREATE TABLE IF NOT EXISTS public."Year"
(
    "ID_year" integer NOT NULL,
    year integer,
    CONSTRAINT "Year_pkey" PRIMARY KEY ("ID_year")
);

ALTER TABLE IF EXISTS public."Country_Power Source"
    ADD CONSTRAINT "Country_Power Source_Country_ID_Country_fkey" FOREIGN KEY ("Country_ID_Country")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Country_Power Source"
    ADD CONSTRAINT "Country_Power Source_Power Source_ID_Power_fkey" FOREIGN KEY ("Power Source_ID_Power")
    REFERENCES public."Power Source" ("ID_Power") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Country_Power Source"
    ADD FOREIGN KEY ("Year_ID_year")
    REFERENCES public."Year" ("ID_year") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Country_Year"
    ADD CONSTRAINT "Country_Year_ConsumePower_ID_fkey" FOREIGN KEY ("ConsumePower_ID")
    REFERENCES public."Power Consumed" ("ID_Consumed") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Country_Year"
    ADD CONSTRAINT "Country_Year_Country_ID_Country_fkey" FOREIGN KEY ("Country_ID_Country")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Country_Year"
    ADD CONSTRAINT "Country_Year_Enviromental_ID_fkey" FOREIGN KEY ("Enviromental_ID")
    REFERENCES public."Environmental Indicator" ("ID_Environmental") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Country_Year_Enviromental_ID_key"
    ON public."Country_Year"("Enviromental_ID");


ALTER TABLE IF EXISTS public."Country_Year"
    ADD CONSTRAINT "Country_Year_GDP_ID_fkey" FOREIGN KEY ("GDP_ID")
    REFERENCES public."GDP" ("ID_GDP") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Country_Year_GDP_ID_key"
    ON public."Country_Year"("GDP_ID");


ALTER TABLE IF EXISTS public."Country_Year"
    ADD CONSTRAINT "Country_Year_IDH_ID_fkey" FOREIGN KEY ("IDH_ID")
    REFERENCES public."IDH" ("ID_IDH") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Country_Year_IDH_ID_key"
    ON public."Country_Year"("IDH_ID");


ALTER TABLE IF EXISTS public."Country_Year"
    ADD CONSTRAINT "Country_Year_Year_ID_year_fkey" FOREIGN KEY ("Year_ID_year")
    REFERENCES public."Year" ("ID_year") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Setor_Year"
    ADD CONSTRAINT "Setor_Year_Setor_ID_Server_fkey" FOREIGN KEY ("Setor_ID_Server")
    REFERENCES public."Setor" ("ID_Server") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Setor_Year"
    ADD CONSTRAINT "Setor_Year_Year_ID_year_fkey" FOREIGN KEY ("Year_ID_year")
    REFERENCES public."Year" ("ID_year") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Setor_Year"
    ADD FOREIGN KEY ("Country_ID_country")
    REFERENCES public."Country" ("ID_Country") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;